### ISSUE TITLE
data files

### ISSUE THREAD

**Issue by msujas** [jonwright/EigerPowderSpatial#1]
Hi,
Is there supposed to be a hyperlink to the data files somewhere? On the readme it says "You will need to edit/modify them for any other detector geometry. If you can log in at ESRF you can find the data files referenced here.", but I can't see where that is. If the data is not sensitive maybe it can be added to the repository to make it easier for users.
Kenny

**Comment by jonwright** [comment]
Thanks for the feedback. We have just uploaded the data to Zenodo : [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.6344000.svg)](https://doi.org/10.5281/zenodo.6344000). Can you let me know if that works for you?

**Comment by msujas** [comment]
Yes, I was able to download the data from there, thanks.

**Comment by msujas** [comment]
Is there an example .par file somewhere? I was able to go through the moduleSpatialPeakSearch notebook, but can't go through the fitpksEiger one.

**Comment by jonwright** [comment]
Probably I should check these in. Here is the one for the first frame:
```
cell__a 5.411
cell__b 5.411
cell__c 5.411
cell_alpha 90.0
cell_beta 90.0
cell_gamma 90.0
cell_lattice_[P,A,B,C,I,F,R] F
chi 0.0
distance 422.15321061257094
fit_tolerance 0.025
min_bin_prob 1e-05
no_bins 10000
o11 1
o12 0
o21 0
o22 -1
omegasign 1.0
t_x 0
t_y 0
t_z 0
tilt_x 0.0
tilt_y -0.00160686467111
tilt_z 0.000325718756829
wavelength 0.22454948836366928
wedge 0.0
weight_hist_intensities 0
y_center 1058.5301834127285
y_size 0.075
z_center 1127.2604699965723
z_size 0.075
```

**Comment by jonwright** [comment]
Initial parameter files are in git now
